### ISSUE TITLE
Getting this error with ZIO 1.0.0

### ISSUE THREAD

**Issue by hmemcpy** [gaelrenoux/tranzactio#13]
(I added tranzactio 0.6.0 in my sbt, upgraded zio to 1.0.0 and cats-interop to 2.1.4.0):

```scala
Exception in thread "main" java.lang.NoClassDefFoundError: zio.Has$AreHas$
	at io.github.gaelrenoux.tranzactio.DatabaseModuleBase.<init>(DatabaseModuleBase.scala:48)
	at io.github.gaelrenoux.tranzactio.doobie.package$Database$.<init>(package.scala:27)
	at io.github.gaelrenoux.tranzactio.doobie.package$Database$.<clinit>(package.scala:27)
```

I'll try to make a small repro...

**Comment by skress** [comment]
0.6.0 is not compatible with ZIO 1.0.0. I had a similar problem and although no source changes were necessary, tranzactio needed to be compiled against ZIO 1.0.0.

The master branch is already updated but afaik there is no published release. You could clone this repo and publish locally to see if it then works for you.

**Comment by PawelJ-PL** [comment]
Hi, I observed similar problem. After compiling master, everything seems to be working fine.
